
import { IStreamWriter } from "../util/StreamWriter";
import { VsixBuilder } from "../util/VsixBuilder";
import { IThemeDefinition } from "./IThemeDefinition";

export class Manifest
{
    static AddInstallationTarget(writer: IStreamWriter, product: string, targetMin: string, targetMax: string, platform: string): void
    {
        writer.writeLine(`    <InstallationTarget Id="${product}" Version="[${targetMin},${targetMax})" >`);
        writer.writeLine(`      <ProductArchitecture>${platform}</ProductArchitecture>`);
        writer.writeLine(`    </InstallationTarget>`);
    }

    static AddManifestToVsix(builder: VsixBuilder, themeDef: IThemeDefinition): void
    {
        const manifest = builder.AddFile("extension.vsixmanifest");

        const targetMin = themeDef.vsTargetMin || "18.0";
        const targetMax = themeDef.vsTargetMax || "19.0";

        manifest.writer.writeLine(`<?xml version="1.0" encoding="utf-8"?>`);
        manifest.writer.writeLine(`<PackageManifest Version="2.0.0" xmlns="http://schemas.microsoft.com/developer/vsx-schema/2011">`);
        manifest.writer.writeLine(`  <Metadata>`);
        manifest.writer.writeLine(`    <Identity Version="${themeDef.version}" Language="en-US" Publisher="${themeDef.author}" Id="${themeDef.extensionIdentity}" />`);
        manifest.writer.writeLine(`    <DisplayName>${themeDef.name}</DisplayName>`);
        manifest.writer.writeLine(`    <Description xml:space="preserve">`);
        manifest.writer.writeLine(`      A Visual Studio theme generated by VsThemix.`);
        manifest.writer.writeLine(`    </Description>`);
        manifest.writer.writeLine(`  </Metadata>`);
        manifest.writer.writeLine(`  <Installation>`);
        this.AddInstallationTarget(manifest.writer, "Microsoft.VisualStudio.Community", targetMin, targetMax, "amd64");
        this.AddInstallationTarget(manifest.writer, "Microsoft.VisualStudio.Community", targetMin, targetMax, "arm64");
        this.AddInstallationTarget(manifest.writer, "Microsoft.VisualStudio.Enterprise", targetMin, targetMax, "amd64");
        this.AddInstallationTarget(manifest.writer, "Microsoft.VisualStudio.Enterprise", targetMin, targetMax, "arm64");
        this.AddInstallationTarget(manifest.writer, "Microsoft.VisualStudio.Pro", targetMin, targetMax, "amd64");
        this.AddInstallationTarget(manifest.writer, "Microsoft.VisualStudio.Pro", targetMin, targetMax, "arm64");
        manifest.writer.writeLine(`  </Installation>`);
        manifest.writer.writeLine(`  <Dependencies>`);
        manifest.writer.writeLine(`    <Dependency Id="Microsoft.Framework.NDP" DisplayName="Microsoft .NET Framework" Version="[4.5,)" />`);
        manifest.writer.writeLine(`  </Dependencies>`);
        manifest.writer.writeLine(`  <Prerequisites>`);
        manifest.writer.writeLine(`    <Prerequisite Id="Microsoft.VisualStudio.Component.CoreEditor" Version="[${targetMin},${targetMax})" DisplayName="Visual Studio core editor" />`);
        manifest.writer.writeLine(`  </Prerequisites>`);
        manifest.writer.writeLine(`  <Assets>`);
        manifest.writer.writeLine(`    <Asset Type="Microsoft.VisualStudio.ColorTheme" Path="extension.pkgdef" />`);
        manifest.writer.writeLine(`  </Assets>`);
        manifest.writer.writeLine(`</PackageManifest>`);
    }
}